spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyc?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456